#' Hente data for Nakke
#'
#' Hente Nakke-data fra staging. Resulterer i dataramma "RegData".
#'
#' @return RegData dataramme
#' @export


NakkeRegData <- function() {

#Kommenter ut variable som ikke er i bruk

     registryName <- "Nakke"
     dbType <- "mysql"

     query <- "SELECT
     ForlopsID,
     PasientID,
     SykehusNavn,
     OprDato,
     Alder,
     AndreRelSykdommer,
     AntallNivaaOpr,
     AntBarn,
#    AntBarnPas,
     Antibiotika,
     AntibiotikaAntDogn,
     AntibiotikaDose,
     AntibiotikaDoseAntall,
     AntibiotikaIntEvtAntDogn,
     AntibiotikaIntKunOprDag,
     AntibiotikaMedikament,
     Arbeidstaus12mnd,
     Arbeidstaus3mnd,
     ArbeidstausPreOp,
     ASAgrad,
     AVD_RESH,
     Avdeling,
#     BakreFusjonDistaltNiv,
#     BakreFusjonProximaltNiv,
#     BakreFusjonSkruer,
#     BakreFusjonStag,
#     BakreFusjonWire,
#     BenGraftAutograft,
#     BenGraftBankben,
#     BenGraftBensubstitutt,
     BMI,
     BMIkategori,
#     CentreID12mnd,
#     CentreID3mnd,
#     CentreIdPas,
     Dagkirurgi,
     DelvisSykemeldtPros12mnd,
     DelvisSykemeldtPros3mnd,
     DelvisSykemeldtProsPreOp,
     DodsDato,
     DodsfallOpphold,
     DodsfallOppholdAnnetSpes,
     EMSblareTarm12mnd,
     EMSblareTarm3mnd,
     EMSblareTarmPreOp,
     EMSgangeFunk12mnd,
     EMSgangeFunk3mnd,
     EMSgangeFunkPreOp,
     EMShandFunk12mnd,
     EMShandFunk3mnd,
     EMShandFunkPreOp,
     EMSkoordinasjon12mnd,
     EMSkoordinasjon3mnd,
     EMSkoordinasjonPreOp,
     EMSnummenhet12mnd,
     EMSnummenhet3mnd,
     EMSnummenhetPreOp,
     EMSscore12mnd,
     EMSscore3mnd,
     EMSscorePreOp,
     EnhverKompl12mnd,
     EnhverKompl3mnd,
     Eq5DScore12mnd,
     Eq5DScore3mnd,
     Eq5DScorePreOp,
     EqAngst12mnd,
     EqAngst3mnd,
     EqAngstPreOp,
     EqGange12mnd,
     EqGange3mnd,
     EqGangePreOp,
     EqPersStell12mnd,
     EqPersStell3mnd,
     EqPersStellPreOp,
     EqSmerte12mnd,
     EqSmerte3mnd,
     EqSmertePreOp,
     EqVanlGjMaal12mnd,
     EqVanlGjMaal3mnd,
     EqVanlGjMaalPreOp,
     Erstatning12mnd,
     Erstatning3mnd,
     ErstatningPreOp,
     ForlopsLaget,
     ForlopsLagetAv,
     ForlopsOppdaterAv,
     ForlopsOppdatert,
     FornoydBeh12mnd,
     FornoydBeh3mnd,
     FriskmeldtDato12mnd,
     FriskmeldtDato3mnd,
     Helsetilst12mnd,
     Helsetilst3mnd,
     HelsetilstPreOp,
     HelsetilstPreOpMissing,
     Hoyde,
     HoydeMissing,
     InngrepType,
     Kjonn,
#    KnivtidSluttMin,
#     KnivtidSluttTimer,
#     KnivtidStartMin,
#     KnivtidStartTimer,
     KnivtidTotalMin,
     KomplDVT12mnd,
     KomplDVT3mnd,
     KomplinfekDyp12mnd,
     KomplinfekDyp3mnd,
     KomplinfekOverfl12mnd,
     KomplinfekOverfl3mnd,
     KomplKraftsvikt12mnd,
     KomplKraftsvikt3mnd,
     KomplLungeEmboli12mnd,
     KomplLungeEmboli3mnd,
     KomplPneumoni12mnd,
     KomplPneumoni3mnd,
     KomplStemme12mnd,
     KomplStemme3mnd,
     KomplSvelging12mnd,
     KomplSvelging3mnd,
     KomplUVI12mnd,
     KomplUVI3mnd,
     LegeskjemaStatus,
     LiggeDognPostop,
     LiggeDognTotalt,
#     MceCentreID,
     Morsmal,
     NDIarbeid12mnd,
     NDIarbeid3mnd,
     NDIarbeidPreOp,
     NDIbilkjoring12mnd,
     NDIbilkjoring3mnd,
     NDIbilkjoringPreOp,
     NDIfritid12mnd,
     NDIfritid3mnd,
     NDIfritidPreOp,
     NDIhodepineE12mnd,
     NDIhodepineE3mnd,
     NDIhodepinePreOp,
     NDIkonsentrasjon12mnd,
     NDIkonsentrasjon3mnd,
     NDIkonsentrasjonPreOp,
     NDIlesing12mnd,
     NDIlesing3mnd,
     NDIlesingPreOp,
     NDIlofting12mnd,
     NDIlofting3mnd,
     NDIloftingPreOp,
     NDIpersStell12mnd,
     NDIpersStell3mnd,
     NDIpersStellPreOp,
     NDIscore12mnd,
     NDIscore3mnd,
     NDIscorePreOp,
     NDIsmerte12mnd,
     NDIsmerte3mnd,
     NDIsmertePreOp,
     NDIsovn12mnd,
     NDIsovn3mnd,
     NDIsovnPreOp,
     NRSsmerteArm12mnd,
     NRSsmerteArm3mnd,
     NRSsmerteArmMissingPreOp,
     NRSsmerteArmPreOp,
     NRSsmerteHodet12mnd,
     NRSsmerteHodet3mnd,
     NRSsmerteHodetMissingPreOp,
     NRSsmerteHodetPreOp,
     NRSsmerteNakke12mnd,
     NRSsmerteNakke3mnd,
     NRSsmerteNakkeMissingPreOp,
     NRSsmerteNakkePreOp,
     NytteOpr12mnd,
     NytteOpr3mnd,
     OperasjonsKategori,
     OppFolgLaget12mnd,
     OppFolgLaget3mnd,
     OppFolgLagetAv12mnd,
     OppFolgLagetAv3mnd,
     OppFolgOppdatert12mnd,
     OppFolgOppdatert3mnd,
     OppFolgOppdatertAv12mnd,
     OppFolgOppdatertAv3mnd,
     OppFolgStatus12mnd,
     OppFolgStatus3mnd,
     OprIndikAnnet,
     OprIndikasjon,
     OprIndikasjonUtfylt,
     OprIndikMyelopati,
     OprIndikMyelopatiMotorisk,
     OprIndikMyelopatiSensorisk,
     OprIndikParese,
     OprIndikPareseGrad,
     OprIndikSmerteLokArm,
     OprIndikSmerteLokNakke,
     OprIndikSmerter,
     OprKode,
     OprMetodeAndre,
     OprMetodeAnnenBakreDekompr,
     OprMetodeBakreFusjon,
     OprMetodeDiskektomi,
     OprMetodeDiskektomiBenblokk,
     OprMetodeDiskektomiCage,
     OprMetodeDiskektomiPlate,
     OprMetodeDiskektomiSkiveprotese,
     OprMetodeForamenotomiBakreBiLat,
     OprMetodeForamenotomiBakreUniLat,
     OprMetodeKirDekompresjon,
     OprMetodeKorpektomi,
     OprMetodeKorpektomiBenblokk,
     OprMetodeKorpektomiBur,
     OprMetodeKorpektomiPlate,
     OprMetodeMikroMakroEndo,
     OprMetodeTilgangBakre,
     OprMetodeTilgangFremre,
     OprMetodeTilgangFremreH,
     OprMetodeTilgangFremreV,
     ORG_RESH,
     Organisasjon,
     Parese12mnd,
     Parese3mnd,
     PareseDager,
     ParesePreOp,
     PareseTimer,
     PareseUker,
     PareseVarighet,
     PasientDod,
     PasientSkjemaStatus,
     PasLaget,
#     PasLagetAv,
     PasOppdatert,
#     PasOppdatertAv,
#     PatSkjemaLaget,
#     PatSkjemaLagetAv,
#     PatSkjemaOppdatert,
#     PatSkjemaOppdatertAv,
     PerOpEnhverKompl,
     PerOpKomplAnafylaksiI,
     PerOpKomplAnnenNerveskade,
     PerOpKomplAnnet,
     PerOpKomplBlodning,
     PerOpKomplDurarift,
     PerOpKomplFeilplasseringImplant,
     PerOpKomplKardioVaskulare,
     PerOpKomplMedullaskade,
     PerOpKomplNerverotSkade,
     PerOpKomplOpFeilNivaa,
     PerOpKomplOsofagusSkade,
     PerOpKomplRespiratorisk,
     PerOpKomplSkadeStoreBlodkar,
     PostnrPas,
#     PoststedPas,
     RadiologiCt,
     RadiologiMr,
     RadiologiMyelografi,
     RadiologiRtgCcol,
     RadiologiRtgCcolFunkOpptak,
     RadiologiUndersokelseUtfylt,
     RanawatKlassifikasjon,
     Reopr90d,
     ReoprInnen90DagerUfylt,
     RHF,
     RHF_RESH,
     Roker,
     RokerPas,
     RtgFunnANNET,
     RtgFunnCervicalSpStenose,
     RtgFunnDegnerasjonNakke,
     RtgFunnIntrMedHoysingnalMR,
     RtgFunnNormal,
     RtgFunnProlaps,
     RtgFunnRotkanalstenose,
     RtgFunnSpondylolistese,
     RtgFunnUtfylt,
     Saardren,
     SamtykkeStatus,
#     SideNivaaC0_C1,
#     SideNivaaC0C1H,
#     SideNivaaC0C1V,
#     SideNivaaC1C2,
#     SideNivaaC1C2H,
#     SideNivaaC1C2V,
#     SideNivaaC2C3,
#     SideNivaaC2C3H,
#     SideNivaaC2C3V,
#     SideNivaaC3C4,
#     SideNivaaC3C4H,
#     SideNivaaC3C4V,
#     SideNivaaC4C5,
#     SideNivaaC4C5H,
#     SideNivaaC4C5V,
#    SideNivaaC5C6,
#     SideNivaaC5C6H,
#     SideNivaaC5C6V,
#    SideNivaaC6C7,
#    SideNivaaC6C7H,
#    SideNivaaC6C7V,
#    SideNivaaC7TH1,
#     SideNivaaC7TH1H,
#    SideNivaaC7TH1V,
     SivilStatus,
#     SivilStatusPas,
     SmerteLokOverEks12mnd,
     SmerteLokOverEks3mnd,
     SmerteLokOverEksPreOp,
     SmerteLokSide12mnd,
     SmerteLokSide3mnd,
     SmerteLokSidePreOp,
     Smertestill12mnd,
     Smertestill3mnd,
     SmertestillBruk12mnd,
     SmertestillBruk3mnd,
     SmertestillBrukPreOp,
     SmertestillPreOp,
     Snuser,
     SnuserPas,
     StatusKtr12mnd,
     StatusKtr3mnd,
     SykdAnnenendokrin,
     SykdAnnenreumatisk,
     SykdAnnet,
     SykdBechtrew,
     SykdCarpalTunnelSyndr,
     SykdCerebrovaskular,
     SykdDepresjonAngst,
     SykdHjertekar,
     SykdHodepine,
     SykdHypertensjon,
     SykDiabetesMellitus,
     SykdImmunSuprBeh,
     SykdKreft,
     SykdKroniskLunge,
     SykdKroniskNevrologisk,
     SykdKrSmerterMuskelSkjelSyst,
     SykdOsteoporose,
     SykdReumatoidartritt,
     SykdSkulderImpigment,
     SykdVaskularClaudicatio,
     SykdWhiplashNakke,
     SymptVarighetArmer,
     SymptVarighetNakkeHode,
     SymptVarighetSmerterUker,
     TidlOpr,
#     TidlOprAnnetNiv,
     TidlOprAntall,
#     TidlOprNei,
#     TidlOprSammeNiv,
     TidlSkulderPlager12mnd,
     TidlSkulderPlager3mnd,
     TidlSkulderPlagerPreOp,
     Uforetrygd12mnd,
     Uforetrygd3mnd,
     UforetrygdPreOp,
#     UforeTrygdPros12mnd,
#     UforeTrygdPros3mnd,
#     UforeTrygdProsPreOp,
#     UsEmgNevrografi,
     UsRotblokkade,
     Utdanning,
#     UtdanningPas,
     UtDato,
     UtfyltDato12mnd,
     UtfyltDato3mnd,
     UtfyltDatoLegeskjema,
     UtfyltDatoPas,
     VarighetSykeMeld12mnd,
     VarighetSykeMeld3mnd
#     Vekt,
#     YrkeFysiskeKrav
FROM
     Nakke"

#GJØRE UTVALG (også) HER...?

     RegData <- rapbase::LoadRegData(registryName, query, dbType)

#     cast(BirthDt as CHAR(10)) AS BirthDt,
#     HosptlDy+'0' AS HosptlDy,
#     FROM
 #    norScir
  #   WHERE
   #  SkjemaID=1"


     return(RegData)
}
